In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('Synthetic_Transaction_Risk_Dataset.xlsx')

In [4]:
df.head()

,TransactionID,Timestamp,CustomerID,MerchantID,MerchantCategory,City,State,PaymentMethod,DeviceType,Amount,TransactionHour,IsWeekend,AccountAgeDays,PrevTxn24H,AvgCustomerAmount,AmountDeviation,MerchantRiskScore,DeviceChanged,LocationChanged,IsFraud
0,TX0000001,2025-09-02 10:50:00,C01334,M0410,Fashion,Jaipur,Rajasthan,Credit Card,Windows,503.13,10,0,1359,0,441.11,0.14,0.16,0,0,0
1,TX0000002,2025-07-17 18:48:00,C02203,M0379,Fuel,Pune,Maharashtra,Credit Card,iPhone,2360.42,18,0,1072,1,2439.00,-0.03,0.97,0,0,0
2,TX0000003,2025-09-02 20:40:00,C02304,M0195,Food,Pune,Maharashtra,Debit Card,Android,1940.09,20,0,228,2,2080.68,-0.07,0.50,0,0,0
3,TX0000004,2025-10-23 11:46:00,C01084,M0051,Grocery,Pune,Maharashtra,Wallet,iPhone,1452.12,11,0,725,3,765.94,0.90,0.93,1,0,0
4,TX0000005,2025-09-21 08:07:00,C00820,M0423,Electronics,Jaipur,Rajasthan,Credit Card,Android,519.49,8,1,403,2,3362.47,-0.85,0.93,0,0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TransactionID      10000 non-null  object
 1   Timestamp          10000 non-null  object
 2   CustomerID         10000 non-null  object
 3   MerchantID         10000 non-null  object
 4   MerchantCategory   10000 non-null  object
 5   City               10000 non-null  object
 6   State              10000 non-null  object
 7   PaymentMethod      10000 non-null  object
 8   DeviceType         10000 non-null  object
 9   Amount             10000 non-null  float64
 10  TransactionHour    10000 non-null  int64
 11  IsWeekend          10000 non-null  int64
 12  AccountAgeDays     10000 non-null  int64
 13  PrevTxn24H         10000 non-null  int64
 14  AvgCustomerAmount  10000 non-null  float64
 15  AmountDeviation    10000 non-null  float64
 16  MerchantRiskScore  10000 non-null  float64
 17  DeviceChanged      10000 non-null  int64
 18  LocationChanged    10000 non-null  int64
 19  IsFraud            10000 non-null  int64
dtypes: float64(4), int64(7), object(9)
memory usage: 1.5+ MB

In [7]:
df.describe()

,Amount,TransactionHour,IsWeekend,AccountAgeDays,PrevTxn24H,AvgCustomerAmount,AmountDeviation,MerchantRiskScore,DeviceChanged,LocationChanged,IsFraud
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000
mean,2527.963533,11.548300,0.284100,1502.06930,2.577900,2507.967874,0.007784,0.498533,0.084100,0.0508,0.044500
std,1988.117224,6.946286,0.451007,858.20944,1.850966,1183.798971,0.575922,0.288178,0.277552,0.2196,0.206213
min,20.000000,0.000000,0.000000,10.00000,0.000000,100.000000,-1.000000,0.000000,0.000000,0.0000,0.000000
25%,981.375000,5.000000,0.000000,766.00000,1.000000,1678.172500,-0.410000,0.250000,0.000000,0.0000,0.000000
50%,2174.195000,12.000000,0.000000,1504.00000,2.000000,2512.360000,-0.010000,0.500000,0.000000,0.0000,0.000000
75%,3634.487500,18.000000,1.000000,2235.25000,4.000000,3308.607500,0.410000,0.750000,0.000000,0.0000,0.000000
max,14610.990000,23.000000,1.000000,3000.00000,11.000000,6753.270000,2.350000,1.000000,1.000000,1.0000,1.000000

In [12]:
df[df['TransactionID'].duplicated()].count()

TransactionID        0
Timestamp            0
CustomerID           0
MerchantID           0
MerchantCategory     0
City                 0
State                0
PaymentMethod        0
DeviceType           0
Amount               0
TransactionHour      0
IsWeekend            0
AccountAgeDays       0
PrevTxn24H           0
AvgCustomerAmount    0
AmountDeviation      0
MerchantRiskScore    0
DeviceChanged        0
LocationChanged      0
IsFraud              0
dtype: int64

In [21]:
fraud_per = (df['IsFraud'] == 1).sum()/df.shape[0]*100

In [24]:
n_merchant = df['MerchantID'].nunique()

In [26]:
n_customer = df['CustomerID'].nunique()